# Generated by Django 4.2.15 on 2025-11-30 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerModelFour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeekerModelTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("python_experience", models.IntegerField(null=True)),
                ("java_experience", models.IntegerField(null=True)),
                (
                    "javascript_experience",
                    models.IntegerField(
                        null=True, verbose_name="JavaScript Experience"
                    ),
                ),
                (
                    "cplusplus_experience",
                    models.IntegerField(null=True, verbose_name="C++ Experience"),
                ),
                (
                    "csharp_experience",
                    models.IntegerField(null=True, verbose_name="C# Experience"),
                ),
                ("ruby_experience", models.IntegerField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeekerModelThree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("react_experience", models.IntegerField(null=True)),
                (
                    "vue_experience",
                    models.IntegerField(null=True, verbose_name="Vue.js Experience"),
                ),
                ("angular_experience", models.IntegerField(null=True)),
                ("django_experience", models.IntegerField(null=True)),
                ("flask_experience", models.IntegerField(null=True)),
                ("ruby_on_rails_experience", models.IntegerField(null=True)),
                (
                    "fastapi_experience",
                    models.IntegerField(null=True, verbose_name="FastAPI Experience"),
                ),
                ("laravel_experience", models.IntegerField(null=True)),
                (
                    "express_experience",
                    models.IntegerField(
                        null=True, verbose_name="Express.js Experience"
                    ),
                ),
                ("springboot_experience", models.IntegerField(null=True)),
                (
                    "aspnet_experience",
                    models.IntegerField(null=True, verbose_name="ASP.NET Experience"),
                ),
                ("oracle_experience", models.IntegerField(null=True)),
                (
                    "mysql_experience",
                    models.IntegerField(null=True, verbose_name="mySQL Experience"),
                ),
                (
                    "sqlite_experience",
                    models.IntegerField(null=True, verbose_name="SQLite Experience"),
                ),
                ("mongodb_experience", models.IntegerField(null=True)),
                (
                    "postgresql_experience",
                    models.IntegerField(
                        null=True, verbose_name="PostgreSQL Experience"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeekerModelOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30, null=True)),
                ("last_name", models.CharField(max_length=30, null=True)),
                ("total_years_of_experience", models.IntegerField(null=True)),
                ("html_experience", models.IntegerField(null=True)),
                (
                    "css_experience",
                    models.IntegerField(null=True, verbose_name="CSS Experience"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[("seeker", "Job Seeker"), ("employer", "Employer")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployerModelTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("python_experience", models.IntegerField(null=True)),
                ("java_experience", models.IntegerField(null=True)),
                (
                    "javascript_experience",
                    models.IntegerField(
                        null=True, verbose_name="JavaScript Experience"
                    ),
                ),
                (
                    "cplusplus_experience",
                    models.IntegerField(null=True, verbose_name="C++ Experience"),
                ),
                (
                    "csharp_experience",
                    models.IntegerField(null=True, verbose_name="C# Experience"),
                ),
                ("ruby_experience", models.IntegerField(null=True)),
                (
                    "employer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployerModelThree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("react_experience", models.IntegerField(null=True)),
                (
                    "vue_experience",
                    models.IntegerField(null=True, verbose_name="Vue.js Experience"),
                ),
                ("angular_experience", models.IntegerField(null=True)),
                ("django_experience", models.IntegerField(null=True)),
                ("flask_experience", models.IntegerField(null=True)),
                ("ruby_on_rails_experience", models.IntegerField(null=True)),
                (
                    "fastapi_experience",
                    models.IntegerField(null=True, verbose_name="FastAPI Experience"),
                ),
                ("laravel_experience", models.IntegerField(null=True)),
                (
                    "express_experience",
                    models.IntegerField(
                        null=True, verbose_name="Express.js Experience"
                    ),
                ),
                ("springboot_experience", models.IntegerField(null=True)),
                (
                    "aspnet_experience",
                    models.IntegerField(null=True, verbose_name="ASP.NET Experience"),
                ),
                ("oracle_experience", models.IntegerField(null=True)),
                (
                    "mysql_experience",
                    models.IntegerField(null=True, verbose_name="mySQL Experience"),
                ),
                (
                    "sqlite_experience",
                    models.IntegerField(null=True, verbose_name="SQLite Experience"),
                ),
                ("mongodb_experience", models.IntegerField(null=True)),
                (
                    "postgresql_experience",
                    models.IntegerField(
                        null=True, verbose_name="PostgreSQL Experience"
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployerModelOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_years_of_experience", models.IntegerField(null=True)),
                ("html_experience", models.IntegerField(null=True)),
                (
                    "css_experience",
                    models.IntegerField(null=True, verbose_name="CSS Experience"),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
