# Generated by Django 4.2.15 on 2025-11-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("JobFinder_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
