# Generated by Django 4.2.15 on 2025-12-03 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("JobFinder_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobRequirementOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_years_of_experience", models.IntegerField(null=True)),
                ("html_experience", models.IntegerField(null=True)),
                ("css_experience", models.IntegerField(null=True)),
                (
                    "job",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="req_one",
                        to="JobFinder_app.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobRequirementThree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("react_experience", models.IntegerField(null=True)),
                ("vue_experience", models.IntegerField(null=True)),
                ("angular_experience", models.IntegerField(null=True)),
                ("django_experience", models.IntegerField(null=True)),
                ("flask_experience", models.IntegerField(null=True)),
                ("ruby_on_rails_experience", models.IntegerField(null=True)),
                ("fastapi_experience", models.IntegerField(null=True)),
                ("laravel_experience", models.IntegerField(null=True)),
                ("express_experience", models.IntegerField(null=True)),
                ("springboot_experience", models.IntegerField(null=True)),
                ("aspnet_experience", models.IntegerField(null=True)),
                ("oracle_experience", models.IntegerField(null=True)),
                ("mysql_experience", models.IntegerField(null=True)),
                ("sqlite_experience", models.IntegerField(null=True)),
                ("mongodb_experience", models.IntegerField(null=True)),
                ("postgresql_experience", models.IntegerField(null=True)),
                (
                    "job",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="req_three",
                        to="JobFinder_app.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobRequirementTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("python_experience", models.IntegerField(null=True)),
                ("java_experience", models.IntegerField(null=True)),
                ("javascript_experience", models.IntegerField(null=True)),
                ("cplusplus_experience", models.IntegerField(null=True)),
                ("csharp_experience", models.IntegerField(null=True)),
                ("ruby_experience", models.IntegerField(null=True)),
                (
                    "job",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="req_two",
                        to="JobFinder_app.job",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="EmployerModelFour",),
        migrations.RemoveField(model_name="employermodelthree", name="employer",),
        migrations.RemoveField(model_name="employermodeltwo", name="employer",),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(name="EmployerModelOne",),
        migrations.DeleteModel(name="EmployerModelThree",),
        migrations.DeleteModel(name="EmployerModelTwo",),
    ]
