# Generated by Django 4.2.15 on 2025-11-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobFinder_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seekermodel",
            name="new_field",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
