# Generated by Django 4.2.15 on 2025-11-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobFinder_app", "0002_seekermodel_new_field"),
    ]

    operations = [
        migrations.RemoveField(model_name="seekermodel", name="new_field",),
        migrations.AlterField(
            model_name="seekermodel",
            name="first_name",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
