# Generated by Django 4.2.15 on 2025-11-30 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("JobFinder_app", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="employermodelone", name="employer",),
        migrations.RemoveField(model_name="employermodelthree", name="employer",),
        migrations.RemoveField(model_name="employermodeltwo", name="employer",),
        migrations.AddField(
            model_name="employermodelone",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employermodelthree",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employermodeltwo",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
