# Generated by Django 4.2.15 on 2025-12-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobFinder_app", "0002_job_jobrequirementone_jobrequirementthree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="interview_questions",
            field=models.TextField(
                blank=True, help_text="Enter one question per line.", null=True
            ),
        ),
    ]
