# Generated by Django 4.2.15 on 2025-11-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobFinder_app", "0003_remove_seekermodel_new_field_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seekermodel",
            name="last_name",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
