# Generated by Django 4.2.15 on 2025-11-30 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("JobFinder_app", "0003_remove_employermodelone_employer_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="employermodelone", name="user",),
        migrations.RemoveField(model_name="employermodelthree", name="user",),
        migrations.RemoveField(model_name="employermodeltwo", name="user",),
        migrations.AddField(
            model_name="employermodelone",
            name="employer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employermodelthree",
            name="employer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employermodeltwo",
            name="employer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
