# Generated by Django 4.2.15 on 2025-11-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobFinder_app", "0004_alter_seekermodel_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_years_of_experience", models.IntegerField(null=True)),
                ("html_experience", models.IntegerField(null=True)),
                (
                    "css_experience",
                    models.IntegerField(null=True, verbose_name="CSS Experience"),
                ),
                ("python_experience", models.IntegerField(null=True)),
                ("java_experience", models.IntegerField(null=True)),
                (
                    "javascript_experience",
                    models.IntegerField(
                        null=True, verbose_name="JavaScript Experience"
                    ),
                ),
                (
                    "cplusplus_experience",
                    models.IntegerField(null=True, verbose_name="C++ Experience"),
                ),
                (
                    "csharp_experience",
                    models.IntegerField(null=True, verbose_name="C# Experience"),
                ),
                ("ruby_experience", models.IntegerField(null=True)),
                ("react_experience", models.IntegerField(null=True)),
                (
                    "vue_experience",
                    models.IntegerField(null=True, verbose_name="Vue.js Experience"),
                ),
                ("angular_experience", models.IntegerField(null=True)),
                ("django_experience", models.IntegerField(null=True)),
                ("flask_experience", models.IntegerField(null=True)),
                ("ruby_on_rails_experience", models.IntegerField(null=True)),
                (
                    "fastapi_experience",
                    models.IntegerField(null=True, verbose_name="FastAPI Experience"),
                ),
                ("laravel_experience", models.IntegerField(null=True)),
                (
                    "express_experience",
                    models.IntegerField(
                        null=True, verbose_name="Express.js Experience"
                    ),
                ),
                ("springboot_experience", models.IntegerField(null=True)),
                (
                    "aspnet_experience",
                    models.IntegerField(null=True, verbose_name="ASP.NET Experience"),
                ),
                ("oracle_experience", models.IntegerField(null=True)),
                (
                    "mysql_experience",
                    models.IntegerField(null=True, verbose_name="mySQL Experience"),
                ),
                (
                    "sqlite_experience",
                    models.IntegerField(null=True, verbose_name="SQLite Experience"),
                ),
                ("mongodb_experience", models.IntegerField(null=True)),
                (
                    "postgresql_experience",
                    models.IntegerField(
                        null=True, verbose_name="PostgreSQL Experience"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="seekermodel", name="total_years_experience",
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="angular_experience",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="aspnet_experience",
            field=models.IntegerField(null=True, verbose_name="ASP.NET Experience"),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="cplusplus_experience",
            field=models.IntegerField(null=True, verbose_name="C++ Experience"),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="csharp_experience",
            field=models.IntegerField(null=True, verbose_name="C# Experience"),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="css_experience",
            field=models.IntegerField(null=True, verbose_name="CSS Experience"),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="django_experience",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="express_experience",
            field=models.IntegerField(null=True, verbose_name="Express.js Experience"),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="fastapi_experience",
            field=models.IntegerField(null=True, verbose_name="FastAPI Experience"),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="flask_experience",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="html_experience",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="java_experience",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="javascript_experience",
            field=models.IntegerField(null=True, verbose_name="JavaScript Experience"),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="laravel_experience",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="mongodb_experience",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="mysql_experience",
            field=models.IntegerField(null=True, verbose_name="mySQL Experience"),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="oracle_experience",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="postgresql_experience",
            field=models.IntegerField(null=True, verbose_name="PostgreSQL Experience"),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="python_experience",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="react_experience",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="ruby_experience",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="ruby_on_rails_experience",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="springboot_experience",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="sqlite_experience",
            field=models.IntegerField(null=True, verbose_name="SQLite Experience"),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="total_years_of_experience",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="seekermodel",
            name="vue_experience",
            field=models.IntegerField(null=True, verbose_name="Vue.js Experience"),
        ),
    ]
