# Generated by Django 4.2.15 on 2025-11-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "JobFinder_app",
            "0006_seekermodelone_seekermodelthree_seekermodeltwo_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerModelOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_years_of_experience", models.IntegerField(null=True)),
                ("html_experience", models.IntegerField(null=True)),
                (
                    "css_experience",
                    models.IntegerField(null=True, verbose_name="CSS Experience"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployerModelThree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("react_experience", models.IntegerField(null=True)),
                (
                    "vue_experience",
                    models.IntegerField(null=True, verbose_name="Vue.js Experience"),
                ),
                ("angular_experience", models.IntegerField(null=True)),
                ("django_experience", models.IntegerField(null=True)),
                ("flask_experience", models.IntegerField(null=True)),
                ("ruby_on_rails_experience", models.IntegerField(null=True)),
                (
                    "fastapi_experience",
                    models.IntegerField(null=True, verbose_name="FastAPI Experience"),
                ),
                ("laravel_experience", models.IntegerField(null=True)),
                (
                    "express_experience",
                    models.IntegerField(
                        null=True, verbose_name="Express.js Experience"
                    ),
                ),
                ("springboot_experience", models.IntegerField(null=True)),
                (
                    "aspnet_experience",
                    models.IntegerField(null=True, verbose_name="ASP.NET Experience"),
                ),
                ("oracle_experience", models.IntegerField(null=True)),
                (
                    "mysql_experience",
                    models.IntegerField(null=True, verbose_name="mySQL Experience"),
                ),
                (
                    "sqlite_experience",
                    models.IntegerField(null=True, verbose_name="SQLite Experience"),
                ),
                ("mongodb_experience", models.IntegerField(null=True)),
                (
                    "postgresql_experience",
                    models.IntegerField(
                        null=True, verbose_name="PostgreSQL Experience"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployerModelTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("python_experience", models.IntegerField(null=True)),
                ("java_experience", models.IntegerField(null=True)),
                (
                    "javascript_experience",
                    models.IntegerField(
                        null=True, verbose_name="JavaScript Experience"
                    ),
                ),
                (
                    "cplusplus_experience",
                    models.IntegerField(null=True, verbose_name="C++ Experience"),
                ),
                (
                    "csharp_experience",
                    models.IntegerField(null=True, verbose_name="C# Experience"),
                ),
                ("ruby_experience", models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(name="EmployerModel",),
    ]
