# Generated by Django 4.2.15 on 2025-11-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "JobFinder_app",
            "0007_employermodelone_employermodelthree_employermodeltwo_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
