# Generated by Django 4.2.15 on 2025-12-11 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("JobFinder_app", "0010_accesslog_accesspurchase_delete_employeraccess"),
    ]

    operations = [
        migrations.RemoveField(model_name="accesspurchase", name="price",),
        migrations.RemoveField(
            model_name="accesspurchase", name="stripe_checkout_session_id",
        ),
        migrations.RemoveField(
            model_name="accesspurchase", name="stripe_payment_intent_id",
        ),
        migrations.RemoveField(model_name="accesspurchase", name="via_credits",),
        migrations.RemoveField(model_name="accesspurchase", name="via_stripe",),
        migrations.AddField(
            model_name="accesspurchase",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accesspurchase",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="accesspurchase",
            name="action",
            field=models.CharField(
                choices=[
                    ("interview", "Interview Access"),
                    ("resume", "Resume Access"),
                    ("hire", "Hire / Direct Contact"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="accesspurchase",
            name="seeker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_purchased_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(name="AccessLog",),
    ]
