# Generated by Django 6.0 on 2025-12-17 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobFinder_app", "0012_employeraccess_delete_accesspurchase"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("software", "Software Engineering"),
                    ("machinist", "Machinist / Fabrication"),
                ],
                default="software",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MachinistExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("years_experience", models.PositiveIntegerField(default=0)),
                ("blueprint_reading", models.PositiveIntegerField(default=0)),
                ("cnc_milling", models.PositiveIntegerField(default=0)),
                ("cnc_turning", models.PositiveIntegerField(default=0)),
                ("manual_lathe", models.PositiveIntegerField(default=0)),
                ("manual_mill", models.PositiveIntegerField(default=0)),
                ("welding", models.PositiveIntegerField(default=0)),
                ("fabrication", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MachinistJobRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("years_experience", models.IntegerField(default=0)),
                ("blueprint_reading", models.IntegerField(default=0)),
                ("cnc_milling", models.IntegerField(default=0)),
                ("cnc_turning", models.IntegerField(default=0)),
                ("manual_lathe", models.IntegerField(default=0)),
                ("manual_mill", models.IntegerField(default=0)),
                ("welding", models.PositiveIntegerField(default=0)),
                ("fabrication", models.PositiveIntegerField(default=0)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machinist_requirements",
                        to="JobFinder_app.job",
                    ),
                ),
            ],
        ),
    ]
