# Generated by Django 6.0 on 2025-12-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobFinder_app", "0013_job_job_type_machinistexperience_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machinistexperience",
            name="blueprint_reading",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="machinistexperience",
            name="cnc_milling",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="machinistexperience",
            name="cnc_turning",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="machinistexperience",
            name="fabrication",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="machinistexperience",
            name="manual_lathe",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="machinistexperience",
            name="manual_mill",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="machinistexperience",
            name="welding",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="machinistexperience",
            name="years_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
