# Generated by Django 6.0 on 2025-12-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobFinder_app", "0013_job_job_type_machinistexperience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="require_video_interview",
            field=models.BooleanField(
                default=False,
                help_text="Require candidates to submit video responses to interview questions",
            ),
        ),
    ]
