# Generated by Django 6.0 on 2025-12-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobFinder_app", "0014_job_require_video_interview"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewassignment",
            name="require_video",
            field=models.BooleanField(default=False),
        ),
    ]
