# Generated by Django 6.0 on 2025-12-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobFinder_app", "0015_interviewassignment_require_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewresponse",
            name="test_answer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="interviewresponse",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="interview_videos/"
            ),
        ),
    ]
