# Generated by Django 5.2.1 on 2025-12-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobFinder_app", "0016_interviewresponse_test_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinistexperience",
            name="minimum_hourly_pay",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
