# Generated by Django 5.2.1 on 2025-12-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobFinder_app", "0017_machinistexperience_minimum_hourly_pay"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrequirementone",
            name="minimum_yearly_salary",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="machinistjobrequirement",
            name="minimum_hourly_pay",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seekermodelone",
            name="minimum_yearly_salary",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
