# Generated by Django 6.0 on 2026-01-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("JobFinder_app", "0018_jobrequirementone_minimum_yearly_salary_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interviewresponse",
            old_name="test_answer",
            new_name="text_answer",
        ),
    ]
