# Generated by Django 6.0 on 2026-01-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobFinder_app", "0020_hire"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="zip_code",
            field=models.CharField(
                blank=True, help_text="Used for job matching", max_length=10, null=True
            ),
        ),
    ]
