# Generated by Django 6.0 on 2026-01-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobFinder_app", "0021_profile_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_remote",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="search_radius_miles",
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name="job",
            name="zip_code",
            field=models.CharField(default=24503, max_length=10),
            preserve_default=False,
        ),
    ]
