# Generated by Django 6.0 on 2026-01-14 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("JobFinder_app", "0022_job_is_remote_job_search_radius_miles_job_zip_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job", old_name="is_remote", new_name="remote_only",
        ),
    ]
